### ISSUE TITLE
No SQL scheme

### ISSUE THREAD

**Issue by markc** [kiran94/FamilyTree#1]
Hi, this looks interesting but there is no SQL schema and I can't see how one would add and edit any entries?

**Comment by kiran94** [comment]
Hi, Thanks for your interest. I will upload a SQL schema by the end of the day. Regarding the add and edit entries, I have been meaning to do it but have been busy with work. It will be done soon!

**Comment by kiran94** [comment]
Ability to add members to the database has been implemented.
